### ISSUE TITLE
Freezetime's access to every imported module's attribute triggers celery's deprecation warnings

### ISSUE THREAD

**Issue by dnathe4th** [spulec/freezegun#101]
Since https://github.com/spulec/freezegun/commit/70518d630c71a37d3c651dee7b73d347b5d75405 freezegun has been fetching every attribute from every imported module to check if it matches one of the patchable date. However, the celery package imports a number of modules that throw deprecation warnings on their access.  Celery slightly complicates the tracking down of this issue because it implements some LazyModule functionality so the deprecation warnings show when first accessed. Normally this prevents the warnings from showing to developer unless they intended to use a deprecated module, but since freezegun touches ever attribute on every module, the warning is always thrown.

**Comment by spulec** [comment]
The easiest workaround for now is to pass the [`ignore` parameter](https://github.com/spulec/freezegun/blob/master/freezegun/api.py#L372-L385) with the deprecated modules. That obviously isn't ideal, but I don't have a better answer right now.

Suggestions welcome.

**Comment by ask** [comment]
You could catch all warnings and ignore them using `with warnings.catch_warnings(..)`

**Comment by charlax** [comment]
A similar thing happens with pytest:

```
Traceback (most recent call last):
  File "/Users/ca/.virtualenvs/package/lib/python2.7/site-packages/freezegun/api.py", line 427, in wrapper
    with self:
  File "/Users/ca/.virtualenvs/package/lib/python2.7/site-packages/freezegun/api.py", line 320, in __enter__
    self.start()
  File "/Users/ca/.virtualenvs/package/lib/python2.7/site-packages/freezegun/api.py", line 366, in start
    for module_attribute in dir(module):
  File "/Users/ca/.virtualenvs/package/lib/python2.7/site-packages/py/_apipkg.py", line 143, in __dict__
    self.__makeattr(name)
  File "/Users/ca/.virtualenvs/package/lib/python2.7/site-packages/py/_apipkg.py", line 125, in __makeattr
    result = importobj(modpath, attrname)
  File "/Users/ca/.virtualenvs/package/lib/python2.7/site-packages/py/_apipkg.py", line 48, in importobj
    module = __import__(modpath, None, None, ['__doc__'])
  File "/Users/ca/.virtualenvs/package/lib/python2.7/site-packages/py/_code/assertion.py", line 89, in <module>
    from py._code._assertionold import interpret as reinterpret_old
  File "/Users/ca/.virtualenvs/package/lib/python2.7/site-packages/py/_code/_assertionold.py", line 3, in <module>
    from compiler import parse, ast, pycodegen
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/compiler/__init__.py", line 27, in <module>
    DeprecationWarning, stacklevel=2)
DeprecationWarning: The compiler package is deprecated and removed in Python 3.x.
```

I'm using the latest version of pytest.

**Comment by charlax** [comment]
I added `py` to ignore to fix it.
