### ISSUE TITLE
freeze_time breaks when cffi is installed

### ISSUE THREAD

**Issue by mmailhot** [spulec/freezegun#123]
When `cffi` is installed freeze_time raises an exception on start

```
Traceback (most recent call last):
  File "some test", line 208
    with freezegun.freeze_time(datetime.utcnow() + timedelta(seconds=Config.SESSION_TTL + 1)):
  File "/usr/local/lib/python2.7/site-packages/freezegun/api.py", line 257, in __enter__
    self.start()
  File "/usr/local/lib/python2.7/site-packages/freezegun/api.py", line 292, in start
    attribute_value = getattr(module, module_attribute)
TypeError: getattr(): attribute name must be string
```

The culprit is that calling `dir` on one of the modules in `cffi` returns a few attributes that are integers, and fail when passed into `getattr`. There is already a try catch block around this, so either this should be extended to catch `TypeError`s or it should be checked that all attribute names are strings.

Tested on `freezegun` 0.3.3 and 0.3.5, with cffi 1.4.2

**Comment by adepue** [comment]
+1 this is breaking for me as well

**Comment by droanr** [comment]
+1 this breaks.

**Comment by tomo-otsuka** [comment]
+1

**Comment by ibiternas** [comment]
+1

**Comment by adepue** [comment]
@mmailhot Opened a PR for fixing this.

**Comment by spulec** [comment]
Fixed with https://github.com/spulec/freezegun/pull/125

**Comment by olivierlefloch** [comment]
Can we get a release for this please? cc @spulec Thanks!

**Comment by peterbe** [comment]
FYI, upgrading to 0.3.6 solved this for me. So I guess that answers @olivierlefloch's question :)

**Comment by olivierlefloch** [comment]
Thanks a lot! (and thanks for the ping :) )

**Comment by JanMalte** [comment]
0.3.6 didn't solved it for me. As soon as I have `cffi` installed, the tests of my project fail with the following exception:
```
Traceback (most recent call last):
  File "/project/env/lib/python3.4/site-packages/django_dynamic_fixture/ddf.py", line 539, in get
    self._save_the_instance(instance)
  File "/project/env/lib/python3.4/site-packages/django_dynamic_fixture/ddf.py", line 515, in _save_the_instance
    instance.save()
  File "/project/project/project/models.py", line 32, in save
    self.created_date = timezone.now()
  File "/project/env/lib/python3.4/site-packages/django/utils/timezone.py", line 322, in now
    return datetime.utcnow().replace(tzinfo=utc)
  File "/project/env/lib/python3.4/site-packages/freezegun/api.py", line 191, in utcnow
    result = cls._time_to_freeze()
  File "/project/env/lib/python3.4/site-packages/freezegun/api.py", line 196, in _time_to_freeze
    return cls.times_to_freeze[-1]()
IndexError: list index out of range
```

**Comment by ben-davis** [comment]
@JanMalte did you manage to fix this?

**Comment by JanMalte** [comment]
It seems like it is fixed in cffi, but there isn't a new release for cffi yet. The fix is only available in the git repository of cffi.
