### ISSUE TITLE
Missing "dateutils" from requirements.txt

### ISSUE THREAD

**Issue by lamby** [spulec/freezegun#173]
```
$ make test
rm -f .coverage
nosetests  ./tests/
EEEEEEE
======================================================================
ERROR: Failure: ImportError (No module named dateutil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/lamby/git/forks/freezegun/tests/test_class_import.py", line 12, in <module>
    from freezegun import freeze_time
  File "/home/lamby/git/forks/freezegun/freezegun/__init__.py", line 9, in <module>
    from .api import freeze_time
  File "/home/lamby/git/forks/freezegun/freezegun/api.py", line 10, in <module>
    from dateutil import parser
ImportError: No module named dateutil

======================================================================
ERROR: Failure: ImportError (No module named dateutil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/lamby/git/forks/freezegun/tests/test_datetimes.py", line 8, in <module>
    from tests import utils
  File "/home/lamby/git/forks/freezegun/tests/utils.py", line 5, in <module>
    from freezegun.api import FakeDate, FakeDatetime, _is_cpython
  File "/home/lamby/git/forks/freezegun/freezegun/__init__.py", line 9, in <module>
    from .api import freeze_time
  File "/home/lamby/git/forks/freezegun/freezegun/api.py", line 10, in <module>
    from dateutil import parser
ImportError: No module named dateutil

======================================================================
ERROR: Failure: ImportError (No module named dateutil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/lamby/git/forks/freezegun/tests/test_import_alias.py", line 1, in <module>
    from freezegun import freeze_time
  File "/home/lamby/git/forks/freezegun/freezegun/__init__.py", line 9, in <module>
    from .api import freeze_time
  File "/home/lamby/git/forks/freezegun/freezegun/api.py", line 10, in <module>
    from dateutil import parser
ImportError: No module named dateutil

======================================================================
ERROR: Failure: ImportError (No module named dateutil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/lamby/git/forks/freezegun/tests/test_operations.py", line 2, in <module>
    from freezegun import freeze_time
  File "/home/lamby/git/forks/freezegun/freezegun/__init__.py", line 9, in <module>
    from .api import freeze_time
  File "/home/lamby/git/forks/freezegun/freezegun/api.py", line 10, in <module>
    from dateutil import parser
ImportError: No module named dateutil

======================================================================
ERROR: Failure: ImportError (No module named dateutil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/lamby/git/forks/freezegun/tests/test_pickle.py", line 3, in <module>
    from freezegun import freeze_time
  File "/home/lamby/git/forks/freezegun/freezegun/__init__.py", line 9, in <module>
    from .api import freeze_time
  File "/home/lamby/git/forks/freezegun/freezegun/api.py", line 10, in <module>
    from dateutil import parser
ImportError: No module named dateutil

======================================================================
ERROR: Failure: ImportError (No module named dateutil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/lamby/git/forks/freezegun/tests/test_sqlite3.py", line 2, in <module>
    from freezegun import freeze_time
  File "/home/lamby/git/forks/freezegun/freezegun/__init__.py", line 9, in <module>
    from .api import freeze_time
  File "/home/lamby/git/forks/freezegun/freezegun/api.py", line 10, in <module>
    from dateutil import parser
ImportError: No module named dateutil

======================================================================
ERROR: Failure: ImportError (No module named dateutil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/lamby/git/forks/freezegun/.venv/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/lamby/git/forks/freezegun/tests/test_ticking.py", line 5, in <module>
    from freezegun import freeze_time
  File "/home/lamby/git/forks/freezegun/freezegun/__init__.py", line 9, in <module>
    from .api import freeze_time
  File "/home/lamby/git/forks/freezegun/freezegun/api.py", line 10, in <module>
    from dateutil import parser
ImportError: No module named dateutil

Name                 Stmts   Miss  Cover   Missing
--------------------------------------------------
freezegun/__init__       8      6    25%   11-18
freezegun/api          323    314     3%   12-507
--------------------------------------------------
TOTAL                  331    320     3%   
----------------------------------------------------------------------
Ran 7 tests in 0.003s

FAILED (errors=7)
Makefile:8: recipe for target 'test' failed
make: *** [test] Error 1

```

**Comment by spulec** [comment]
A bit unintuitive, but we use requirements.txt for dev requirements and prod requirements are in the setup.py: https://github.com/spulec/freezegun/blob/master/setup.py#L8-L12

**Comment by lamby** [comment]
Ah, okay. Feel free to close :)
