### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by brianmay** [spulec/freezegun#178]
I am seeing this error pseudo-randomly.

django: 1.11.0
freezegun: 0.3.8

Downgrading freezegun to 0.2.2 appears to help. Or maybe this was just random successes. Not sure.

```
Traceback (most recent call last):
  File "/root/venv/3.5/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 244, in get_expiry_date
    modification = kwargs['modification']
KeyError: 'modification'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/venv/3.5/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/venv/3.5/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/venv/3.5/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/root/venv/3.5/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/venv/3.5/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/root/venv/3.5/lib/python3.5/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/root/venv/3.5/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/root/venv/3.5/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/root/venv/3.5/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/root/venv/3.5/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/root/venv/3.5/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/root/venv/3.5/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/root/venv/3.5/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/root/venv/3.5/lib/python3.5/site-packages/django/contrib/auth/views.py", line 90, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/root/venv/3.5/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/root/venv/3.5/lib/python3.5/site-packages/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/root/venv/3.5/lib/python3.5/site-packages/django/contrib/auth/views.py", line 117, in form_valid
    auth_login(self.request, form.get_user())
  File "/root/venv/3.5/lib/python3.5/site-packages/django/contrib/auth/__init__.py", line 135, in login
    request.session.cycle_key()
  File "/root/venv/3.5/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 314, in cycle_key
    self.create()
  File "/root/venv/3.5/lib/python3.5/site-packages/django/contrib/sessions/backends/db.py", line 54, in create
    self.save(must_create=True)
  File "/root/venv/3.5/lib/python3.5/site-packages/django/contrib/sessions/backends/db.py", line 83, in save
    obj = self.create_model_instance(data)
  File "/root/venv/3.5/lib/python3.5/site-packages/django/contrib/sessions/backends/db.py", line 70, in create_model_instance
    expire_date=self.get_expiry_date(),
  File "/root/venv/3.5/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 246, in get_expiry_date
    modification = timezone.now()
  File "/root/venv/3.5/lib/python3.5/site-packages/django/utils/timezone.py", line 243, in now
    return datetime.utcnow().replace(tzinfo=utc)
  File "/root/venv/3.5/lib/python3.5/site-packages/freezegun/api.py", line 195, in utcnow
    result = cls._time_to_freeze()
  File "/root/venv/3.5/lib/python3.5/site-packages/freezegun/api.py", line 200, in _time_to_freeze
    return cls.times_to_freeze[-1]()
IndexError: list index out of range
```

**Comment by spulec** [comment]
How are you using freezegun (decorator, context manager, raw use)?

**Comment by brianmay** [comment]
This was via Gherkin tests. I have a suspicion I know what is happening, although it is truly weird it only happened randomly - and AFAIK only when testing with selenium/Firefox (never when testing selenium/Chrome).

We had a test that did the following:

```
When I login with user "schattin"
Given today's date is 2017-04-29 and time is 5:40h
When I login with user "schattin"
```

The failure occurred on the first login. So I am guessing somehow freezegun was somehow initialized but never given with a date/time. Which may not be the fault of freezegun, I am not really sure how the components interact.

The tests mean while would continue with the second log in, and everything would work fine.

I removed the first login before the time travel, and it has solved the problem.

**Comment by spulec** [comment]
If you look at the traceback, you can see that the freezegun exception is happening only after another exception already happened: `KeyError: 'modification'`

Ideally, freezegun would always be able to cleanup, but if it is being used in the raw use mode, I'm not sure how that will be possible.

**Comment by brianmay** [comment]
That first exception is just this:

```
try:
    modification = kwargs['modification']
except KeyError:
    modification = timezone.now()
```

I would have used an if statement myself, however this isn't my code. Point is however it is not an error here to generate a `KeyError` exception, but expected behaviour when calling this function without any kwargs.

**Comment by spulec** [comment]
Ah, got it. I am confused then. Can you throw some print statements inside of the freezegun `start` and `stop` to see if they are unbalanced?

**Comment by brianmay** [comment]
It looks like to me that ``start`` and ``stop`` are being called equal times.

But: ``_time_to_freeze`` is being called before the first ``start``.

Will try to investigate when/how start is being called.

**Comment by brianmay** [comment]
Oh, yuck. I just changed the code to print "start.1" when start is called, and then "start.2" when it returns, and "get" when ``_time_to_freeze``  is called.  

I get "start.1", "get", and "start.2" in that order.

I am assuming that the start function doesn't actually call ``_time_to_freeze`` function. Please correct me if I am wrong.

I am now suspecting a race condition between two threads, that has nothing to do with freezegun.

**Comment by brianmay** [comment]
Oh I think I understand the race condition now (disclaimer: not tested). I think there are a number of factors, none directly related to freezegun. It looks like in running the tests, we have two threads, one to interact with the web browser, and one to handle server stuff from the client.

```
thread1 --> browser --> thread2 (http server)
```

In thread1 we login to the web browser. However we don't wait for a response. We then execute the next step, which is to freeze the datetime. At this stage the browser gets around to issuing the request to login, and the request is placed and processed in thread2 while thread1 is still busy freezing the time.

**Comment by brianmay** [comment]
I don't think there is any point keeping this bug open. Closing.
