### ISSUE TITLE
AttributeError when just importing freezegun

### ISSUE THREAD

**Issue by azmeuk** [spulec/freezegun#183]
It seems that simply importing freezegun fails with python 2.7, but seems OK with python 3.6.
```bash
$ python2 -c "import freezegun"                                                                                                                                   
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/eloi/dev/richsms/freezegun.py", line 2, in <module>
AttributeError: 'module' object has no attribute 'freeze_time'
```

**Comment by azmeuk** [comment]
My bad. Reinstalling my virtualenv solved this.
