### ISSUE TITLE
Freezegun makes parsedatetime crashes if PyICU is installed

### ISSUE THREAD

**Issue by WhyNotHugo** [spulec/freezegun#207]
This sample code fails is pyicu is installed:

```python
import parsedatetime
from freezegun import freeze_time

with freeze_time('2017-03-17 20:22:19'):
    parsedatetime.Calendar()
```

Traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3.6/site-packages/parsedatetime/__init__.py", line 271, in __init__
    self.ptc = Constants()
  File "/usr/lib/python3.6/site-packages/parsedatetime/__init__.py", line 2379, in __init__
    self.locale = get_icu(self.localeID)
  File "/usr/lib/python3.6/site-packages/parsedatetime/pdt_locales/icu.py", line 105, in get_icu
    s = o.format(datetime.datetime(2003, 10, 30, 11, 45))
icu.InvalidArgsError: (<class 'icu.SimpleDateFormat'>, 'format', (FakeDatetime(2003, 10, 30, 11, 45),))
```

But it works perfectly if PyICU is not installed.

I'm not 100% certain if the issue is here, or on `parsedatetime`'s side (it seems the mix of all three libraries is the only way to reach this crash).

**Comment by spulec** [comment]
It seems that PyICU does some introspection instead of using duck typing. I don't believe there is a way for Freezegun to fix this

**Comment by nattofriends** [comment]
Apparently passing a float timestamp to icu there would work.
