### ISSUE TITLE
AttributeError: module 'uuid' has no attribute '_uuid_generate_time' on Python 3.7.0b1

### ISSUE THREAD

**Issue by mgedmin** [spulec/freezegun#225]
The upcoming Python 3.7 version drops the internal `_uuid_generate_time` function in the `uuid` module, which makes `freezegun` fail on import:

```
Python 3.7.0b1+ (heads/3.7:7f38637853, Feb  1 2018, 13:09:53) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import freezegun
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/py37/lib/python3.7/site-packages/freezegun/__init__.py", line 9, in <module>
    from .api import freeze_time
  File "/tmp/py37/lib/python3.7/site-packages/freezegun/api.py", line 23, in <module>
    real_uuid_generate_time = uuid._uuid_generate_time
AttributeError: module 'uuid' has no attribute '_uuid_generate_time'
```

**Comment by spulec** [comment]
Thanks!
