### ISSUE TITLE
Tests fail with RecursionError 

### ISSUE THREAD

**Issue by kapsh** [spulec/freezegun#234]
I've encountered failed tests on 0.3.10 and current master e962d3d.

```
% tox -e py36
GLOB sdist-make: /tmp/freezegun/setup.py
py36 inst-nodeps: /tmp/freezegun/.tox/dist/freezegun-0.3.10.zip
py36 installed: certifi==2018.1.18,chardet==3.0.4,coverage==3.7.1,coveralls==1.3.0,docopt==0.6.2,freezegun==0.3.10,idna==2.6,mock==2.0.0,nose==1.3.7,pbr==4.0.1,python-dateutil==2.7.2,requests==2.18.4,six==1.11.0,urllib3==1.22
py36 runtests: PYTHONHASHSEED='375160722'
py36 runtests: commands[0] | make test NOSE_ARGS=
rm -f .coverage
nosetests  ./tests/
............F..........S.....FF.F.........F...S......S..FF.F...........................EEEEEETraceback (most recent call last):
  File "/tmp/freezegun/.tox/py36/bin/nosetests", line 11, in <module>
    sys.exit(run_exit())
  File "/tmp/freezegun/.tox/py36/lib/python3.6/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/host/lib64/python3.6/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/tmp/freezegun/.tox/py36/lib/python3.6/site-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/tmp/freezegun/.tox/py36/lib/python3.6/site-packages/nose/core.py", line 65, in run
    stop = time.time()
  File "/tmp/freezegun/freezegun/api.py", line 146, in __call__
    return calendar.timegm(current_time.timetuple()) + current_time.microsecond / 1000000.0
  File "/usr/host/lib64/python3.6/calendar.py", line 601, in timegm
    days = datetime.date(year, month, 1).toordinal() - _EPOCH_ORD + day - 1
  File "/tmp/freezegun/freezegun/api.py", line 211, in __new__
    return real_date.__new__(cls, *args, **kwargs)
  File "/tmp/freezegun/freezegun/api.py", line 211, in __new__
    return real_date.__new__(cls, *args, **kwargs)
  File "/tmp/freezegun/freezegun/api.py", line 211, in __new__
    return real_date.__new__(cls, *args, **kwargs)
  [Previous line repeated 488 more times]
RecursionError: maximum recursion depth exceeded
make: *** [Makefile:9: test] Error 1
ERROR: InvocationError for command '/usr/host/bin/make test NOSE_ARGS=' (exited with code 2)
___________________________________________________________________________________________________________________ summary ___________________________________________________________________________________________________________________
ERROR:   py36: commands failed
```

Same result with py27 environment.
tox -vv output: [recursion.log](https://github.com/spulec/freezegun/files/1886792/recursion.log)

**Comment by spulec** [comment]
Hmmm, I'm struggling to reproduce this.

Any idea what might be different between your environment and Travis-CI?

**Comment by kapsh** [comment]
@spulec I really have no idea. At first I though that the issue could be related to Python 3.6 or Exherbo which I happen to use. However, then I got the same result on Debian and Python 2.7. 
But you can always ask me to provide any other information about system or check something in pdb.

**Comment by spulec** [comment]
Which version of Py36 do you have installed?

Can you try running the first test that is resulting in failure by itself and see if it fails?

**Comment by kapsh** [comment]
Pythons 3.6.5 and 2.7.14  respectively. 

I've tried single runs:
```
tox -e py36 -- tests.test_utils.test_should_not_skip_cpython
tox -e py36 -- tests.test_utils.test_should_skip_non_cpython 
```
and they failed in the same way.

**Comment by foobarna** [comment]
Just wanna share that we are also encountering `RecursionError` in our test suite. Python 3.5/3.4.
They are fairly random, and not the same failing.

**Comment by spulec** [comment]
@foobarna Any idea what might be different between your environment and Travis-CI?

**Comment by tcs76321** [comment]
*Noob open source contributor*

Since the python versions mentioned in this issue are no longer supported at all(<=3.6) could/should this be closed?

**Comment by kapsh** [comment]
Considering versions, issue age, low number of complains — it probably should be closed.
