### ISSUE TITLE
'FakeDate' object has no attribute 'tzinfo'

### ISSUE THREAD

**Issue by erayerdin** [spulec/freezegun#246]
I have this issue in Django test, in which I need to convert a naive date of an object to aware. `tz_offset` argument does not result in any `tzinfo`. An example of test:

```
        instance = self.model.objects.create(
            client=self.user
        )

        tzone = timezone(settings.TIME_ZONE)
        date_val = tzone.localize(instance.date)

        self.assertEqual(date_val.year, 2018)
        self.assertEqual(date_val.month, 4)
        self.assertEqual(date_val.day, 15)
```

Results in:

```
Error
Traceback (most recent call last):
  File "/home/erayerdin/Documents/Projects/Programming/PycharmProjects/ensms/venv/lib/python3.5/site-packages/freezegun/api.py", line 589, in wrapper
    result = func(*args, **kwargs)
  File "/home/erayerdin/Documents/Projects/Programming/PycharmProjects/ensms/sms/tests/test_models.py", line 66, in test_date_normal
    date_val = tzone.localize(instance.date)
  File "/home/erayerdin/Documents/Projects/Programming/PycharmProjects/ensms/venv/lib/python3.5/site-packages/pytz/tzinfo.py", line 317, in localize
    if dt.tzinfo is not None:
AttributeError: 'FakeDate' object has no attribute 'tzinfo'
```

***

# Environment

 - Django 2.0.4
 - pytz 2018.4

**Comment by erayerdin** [comment]
This issue seems to be related to #191 and its referencers. I respectively leave this issue to the authors / owners / main contributors to close.
