### ISSUE TITLE
Test failure with Python 3.7

### ISSUE THREAD

**Issue by felixonmars** [spulec/freezegun#250]
With other dependencies unchanged, test_uuid1_past fails in 3.7 while works fine in 3.6:

```
======================================================================
FAIL: Test that we can go back in time after setting a future date.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-freezegun/src/freezegun-0.3.10/tests/test_uuid.py", line 28, in test_uuid1_future
    assert_equal(time_from_uuid(uuid.uuid1()), future_target)
AssertionError: FakeDatetime(2018, 6, 30, 3, 46, 21, 439978) != datetime.datetime(2056, 2, 6, 14, 3, 21)
    'FakeDatetime(2018, 6, 30, 3, 46, 21, 439978) != datetime.datetime(2056, 2, 6, 14, 3, 21)' = '%s != %s' % _common_shorten_repr(FakeDatetime(2018, 6, 30, 3, 46, 21, 439978), datetime.datetime(2056, 2, 6, 14, 3, 21))
    'FakeDatetime(2018, 6, 30, 3, 46, 21, 439978) != datetime.datetime(2056, 2, 6, 14, 3, 21)' = self._formatMessage('FakeDatetime(2018, 6, 30, 3, 46, 21, 439978) != datetime.datetime(2056, 2, 6, 14, 3, 21)', 'FakeDatetime(2018, 6, 30, 3, 46, 21, 439978) != datetime.datetime(2056, 2, 6, 14, 3, 21)')
>>  raise self.failureException('FakeDatetime(2018, 6, 30, 3, 46, 21, 439978) != datetime.datetime(2056, 2, 6, 14, 3, 21)')


======================================================================
FAIL: Test that we can go forward in time after setting some time in the past.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-freezegun/src/freezegun-0.3.10/tests/test_uuid.py", line 42, in test_uuid1_past
    assert_equal(time_from_uuid(uuid.uuid1()), past_target)
AssertionError: FakeDatetime(2018, 6, 30, 3, 46, 21, 453343) != datetime.datetime(1978, 7, 6, 23, 6, 31)
    'FakeDatetime(2018, 6, 30, 3, 46, 21, 453343) != datetime.datetime(1978, 7, 6, 23, 6, 31)' = '%s != %s' % _common_shorten_repr(FakeDatetime(2018, 6, 30, 3, 46, 21, 453343), datetime.datetime(1978, 7, 6, 23, 6, 31))
    'FakeDatetime(2018, 6, 30, 3, 46, 21, 453343) != datetime.datetime(1978, 7, 6, 23, 6, 31)' = self._formatMessage('FakeDatetime(2018, 6, 30, 3, 46, 21, 453343) != datetime.datetime(1978, 7, 6, 23, 6, 31)', 'FakeDatetime(2018, 6, 30, 3, 46, 21, 453343) != datetime.datetime(1978, 7, 6, 23, 6, 31)')
>>  raise self.failureException('FakeDatetime(2018, 6, 30, 3, 46, 21, 453343) != datetime.datetime(1978, 7, 6, 23, 6, 31)')


Name                    Stmts   Miss  Cover
-------------------------------------------
freezegun/__init__.py       8      0   100%
freezegun/_async.py        11      1    91%
freezegun/api.py          422     26    94%
-------------------------------------------
TOTAL                     441     27    94%
----------------------------------------------------------------------
Ran 93 tests in 0.672s

FAILED (SKIP=1, failures=2)
```

**Comment by mgorny** [comment]
Is this with 0.3.10? 4fdad69659f15a9e62cf4f6c15c9f319276cf9b0 seems to address that.

**Comment by felixonmars** [comment]
Yes it's with 0.3.10. Sorry for missed the fix :3

**Comment by spulec** [comment]
Sounds good; going to close this then.
