### ISSUE TITLE
TypeError: py.test.__dict__ is not a dictionary

### ISSUE THREAD

**Issue by darkcloud1801** [spulec/freezegun#257]
python==3.4.9
python-dateutil==2.6.1
freezegun==0.3.10
django=1.11.15

If I downgrade to freezegun 0.3.9, I dont encounter the issue, but with 0.3.10 I encounter this with django unittests:

Traceback (most recent call last):
  File "/Users/rubin.mendoza/.virtualenvs/sherman-api/lib/python3.4/site-packages/freezegun/api.py", line 420, in setUpClass
    self.start()
  File "/Users/rubin.mendoza/.virtualenvs/sherman-api/lib/python3.4/site-packages/freezegun/api.py", line 520, in start
    module_attrs = _get_cached_module_attributes(mod_name, module)
  File "/Users/rubin.mendoza/.virtualenvs/sherman-api/lib/python3.4/site-packages/freezegun/api.py", line 108, in _get_cached_module_attributes
    global_modules_cache = _get_global_modules_cache()
  File "/Users/rubin.mendoza/.virtualenvs/sherman-api/lib/python3.4/site-packages/freezegun/api.py", line 64, in _get_global_modules_cache
    _setup_modules_cache()
  File "/Users/rubin.mendoza/.virtualenvs/sherman-api/lib/python3.4/site-packages/freezegun/api.py", line 90, in _setup_modules_cache
    _setup_module_cache(module)
  File "/Users/rubin.mendoza/.virtualenvs/sherman-api/lib/python3.4/site-packages/freezegun/api.py", line 100, in _setup_module_cache
    _GLOBAL_MODULES_CACHE[module.__name__] = (_get_module_attributes_hash(module), date_attrs)
  File "/Users/rubin.mendoza/.virtualenvs/sherman-api/lib/python3.4/site-packages/freezegun/api.py", line 104, in _get_module_attributes_hash
    return '{0}-{1}'.format(id(module), hashlib.md5(','.join(dir(module)).encode('utf-8')).hexdigest())
TypeError: py.test.__dict__ is not a dictionary

**Comment by spulec** [comment]
Can you give some more details on how to reproduce? This seems to be some interaction with pytest.

**Comment by georgesequeira** [comment]
I believe the issue is with anything that requires `py` but does not use `py.test`. In my case it was using the tox library.

Here is a test that will cause the same issue to happen:

requirements.txt
```
nose
tox
freezegun
```


testfile.py
```
import unittest
import freezegun.api
import py


class TestFreezegunIssue(unittest.TestCase):
  def test_should_fail(self):
    freezer = freezegun.api.freeze_time("2012-01-01 12:00:00")
    freezer.start()

```


The reason this happens is because the [py/__init__.py](https://github.com/pytest-dev/py/blob/master/py/__init__.py) lazy loads py.test via [apipkg.initpkg](https://github.com/pytest-dev/py/blob/master/py/_vendored_packages/apipkg.py)

when freezegun is looking setting up the module cache, it does a `dir` on py.test but since it's a lazy loaded (and in this case non-existant module) it fails.

**Comment by darkcloud1801** [comment]
The new update fixes this issue.
