### ISSUE TITLE
Unable to make database calls to mysql when freezing time

### ISSUE THREAD

**Issue by maltzj** [spulec/freezegun#310]
I'm encountering issues when attempting to make database queries with time frozen.  I'm using django, so the repro steps are:

**models.py**
```
from django.db import models

# Create your models here.
class TestTable(models.Model):
    start_date = models.DateField()
```

**Test case**
```
from django.test import TestCase
from maltz import models
import freezegun
from datetime import date
from django.db import connection


class ExampleTestCase(TestCase):
    def test_reproduce_case(self):
        with freezegun.freeze_time('2018-09-01'):
            with connection.cursor() as cursor:
                cursor.execute("select * from maltz_testtable where start_date=%(test)", {'test': date(year=2019, day=1, month=1)})
```

**Expected Behavior**: 

I'd expect the above test to complete with 0 rows

**Actual behavior**

```
Traceback (most recent call last):
  File "/Users/maltz/Documents/workspace/maltztest/maltz/tests.py", line 12, in test_reproduce_case
    cursor.execute("select * from maltz_testtable where start_date=%(test)", {'test': date(year=2019, day=1, month=1)})
  File "/Users/maltz/.pyenv/versions/maltz/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/maltz/.pyenv/versions/maltz/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/maltz/.pyenv/versions/maltz/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/maltz/.pyenv/versions/maltz/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/Users/maltz/.pyenv/versions/maltz/lib/python3.6/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/Users/maltz/.pyenv/versions/maltz/lib/python3.6/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "/Users/maltz/.pyenv/versions/maltz/lib/python3.6/site-packages/pymysql/cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "/Users/maltz/.pyenv/versions/maltz/lib/python3.6/site-packages/pymysql/cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "/Users/maltz/.pyenv/versions/maltz/lib/python3.6/site-packages/pymysql/connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "/Users/maltz/.pyenv/versions/maltz/lib/python3.6/site-packages/pymysql/connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "/Users/maltz/.pyenv/versions/maltz/lib/python3.6/site-packages/pymysql/converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "/Users/maltz/.pyenv/versions/maltz/lib/python3.6/site-packages/pymysql/converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "/Users/maltz/.pyenv/versions/maltz/lib/python3.6/site-packages/pymysql/converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'FakeDate' object has no attribute 'translate'
```

It seems like we could fix this by adding a `translate` method onto `FakeDate`, but that seems like it is playing a game of whack-a-mole.  Maybe there's a more scalable solution that will become obvious when it's not 5:00 on a Friday.

**Comment by luser** [comment]
I work with @maltzj and I asked him about this failure and after poking around a bit it looks like the problem is that the list of argument encoders is a `dict` whose keys are types:
https://github.com/PyMySQL/PyMySQL/blob/8eee26692726e7c923186322a68e15e4d98c138e/pymysql/converters.py#L357

...and the fallback is to try text encoding:
https://github.com/PyMySQL/PyMySQL/blob/8eee26692726e7c923186322a68e15e4d98c138e/pymysql/converters.py#L20

Since `FakeDate` is obviously not in that set of types it breaks things. I don't know that there's a super simple way to handle this, the most obvious way to me would be to do something like:
```python
for ty, encoder in mapping:
  if isinstance(val, ty):
    break
else:
    try:
      encoder = mapping[text_type]
    except KeyError:
       raise TypeError("no default type converter defined")
```

**Comment by luser** [comment]
Oh, sorry, that comment would be more useful on the PyMySQL project. It looks like this actually got fixed in freezegun 0.3.12:
https://github.com/spulec/freezegun/commit/e9c46906fe7e96b243b1f7db1a49bcb9b3b60af4

**Comment by maltzj** [comment]
Sorry, I should've been clearer in my initial comment.  This is with freezegun `0.3.12`

**Comment by luser** [comment]
I spent more time looking into this and the crux of the issue for us is that we're using `pytest-django` and that pytest plugin [configures django extremely early in the pytest lifecycle](https://pytest-django.readthedocs.io/en/latest/configuring_django.html#changing-your-app-before-django-gets-set-up). Because of the way PyMySQL is implemented, [it sets up the encoders/decoders per-connection](https://github.com/PyMySQL/PyMySQL/blob/8eee26692726e7c923186322a68e15e4d98c138e/pymysql/connections.py#L303-L305). With the combination of those two things the database connection gets created before any of our tests get loaded and `import freezegun`, so the monkeypatching `freezegun` attempts to do happens too late to take effect. Because of the hook `pytest-django` is using the only real way around this would be to write an entirely separate pytest plugin that imports `freezegun` *before* `pytest-django` configures django.

As a workaround for now I recommended that we simply move `freezegun` from our requirements-dev.txt to requirements.txt and import it in our django `settings.py` so that it can do the monkeypatching before the database connection is created.

**Comment by boxed** [comment]
Thanks for looking into this and finding the cause!

**Comment by luser** [comment]
I was struggling to write a hook or fixture that fixed this and it turns out that my understanding of the problem was incomplete! The bit I missed was that [in Django's MySQL backend](https://github.com/django/django/blob/2.1.7/django/db/backends/mysql/base.py#L42) it makes a copy of the `encoders` dict from PyMySQL and adds another entry. Then [when it creates the database connection](https://github.com/django/django/blob/2.1.7/django/db/backends/mysql/base.py#L189-L193) it passes that dict in as the `conv` parameter which overrides the default, which is why freezegun's monkeypatching was not taking effect!

Presumably one way to fix this would be to ensure that freezegun gets imported before *any* django modules are imported, but the ordering of imports, hooks, and fixtures in our pytest setup is already dizzyingly complex so I settled on wrapping pytest-django's `django_db_setup` fixture and using that to stuff the freezegun encoders into Django's copy like so:
```python
@pytest.fixture(scope="session")
def before_db_setup():
    """Ensure that freezegun's monkeypatching of PyMySQL's parameter encoding dict happens before
    the database connection is created, and also propogate it down into Django's MySQL backend."""
    # This is here because freezegun will modify pymysql.converters on import.
    import freezegun  # noqa
    import pymysql.converters
    from django.db.backends.mysql.base import django_conversions

    # django_conversions is a copy of pymysql.converters.encoders with a few additional items, so
    # copy over the entries for freezegun's types to it.
    for k, v in pymysql.converters.encoders.items():
        if k not in django_conversions:
            django_conversions[k] = v


@pytest.fixture(scope="session")
def django_db_setup(before_db_setup, django_db_setup):
    pass
```
