### ISSUE TITLE
TypeError: fake_time() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by MuslimBeibytuly** [spulec/freezegun#382]
python version - 3.8.0
freezegun==1.0.0
when calling time.time() it throws TypeError: fake_time() takes 0 positional arguments but 1 was given

**Comment by boxed** [comment]
You need to give at least the full stack trace. It would also help seeing your code that triggers this.

**Comment by oaosman84** [comment]
Here's a stack trace from my end:
```
ERROR    django.request:log.py:224 Internal Server Error: /graphql
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
(TRUNCATED INTERNAL CODE)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/throttling.py", line 124, in allow_request
    self.now = self.timer()
TypeError: fake_time() takes 0 positional arguments but 1 was given
```
Interestingly this happens only if I try to run one individual test. If I run the whole test suite (that includes the individual test), the individual test passes, but if I run it alone, it fails.

**Comment by xemxav** [comment]
I report exactly the same problem and stacktrace as @oaosman84. 
No problem when the tests is run with pytest or with the whole test suite with Pycharm but it fails when run individualy.

**Comment by Kub-AT** [comment]
Same here but appears randomly when running whole test suite with pytest
(pytest  + pytest-xdist + pytest-randomly)


```
TypeError: fake_time() takes 0 positional arguments but 1 was given
self = <unittest.case._Outcome object at 0x7f8cfe4dd610>
test_case = <apps.organization.tests.views.test_get_email_from_invite_key.TestGetEmailBasedOnOrganizationInviteKeyView testMethod=test_should_raise_error_key_is_expired>
isTest = True
    @contextlib.contextmanager
    def testPartExecutor(self, test_case, isTest=False):
        old_success = self.success
        self.success = True
        try:
>           yield
/usr/local/lib/python3.9/unittest/case.py:59: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <apps.organization.tests.views.test_get_email_from_invite_key.TestGetEmailBasedOnOrganizationInviteKeyView testMethod=test_should_raise_error_key_is_expired>
result = <TestCaseFunction test_should_raise_error_key_is_expired>
    def run(self, result=None):
        orig_result = result
        if result is None:
            result = self.defaultTestResult()
            startTestRun = getattr(result, 'startTestRun', None)
            if startTestRun is not None:
                startTestRun()
    
        result.startTest(self)
    
        testMethod = getattr(self, self._testMethodName)
        if (getattr(self.__class__, "__unittest_skip__", False) or
            getattr(testMethod, "__unittest_skip__", False)):
            # If the class or method was skipped.
            try:
                skip_why = (getattr(self.__class__, '__unittest_skip_why__', '')
                            or getattr(testMethod, '__unittest_skip_why__', ''))
                self._addSkip(result, self, skip_why)
            finally:
                result.stopTest(self)
            return
        expecting_failure_method = getattr(testMethod,
                                           "__unittest_expecting_failure__", False)
        expecting_failure_class = getattr(self,
                                          "__unittest_expecting_failure__", False)
        expecting_failure = expecting_failure_class or expecting_failure_method   
 ```

Interestingly I don't use freezegun in this test class or this failed test

**Comment by skarzi** [comment]
@oaosman84 I have spotted the same error when using rest_framework's throttling and it fails, because of following line in `throtlling.py`:

>     timer = time.time

https://github.com/encode/django-rest-framework/blob/8812394ed83d7cce0ed5b2c5fcf093269d364b9b/rest_framework/throttling.py#L63

There `timer` is set to `time.time` that is `bultin_function_or_method` object, so it works when called as a method (`self.timer()`), but when we use `freezegun` to mock the time then `time.time` is replaced with [`fake_time`](https://github.com/spulec/freezegun/blob/4685cb90c82c5fbebceae95fcfd4990dc3be2b8d/freezegun/api.py#L195) that is regular `function` object that doesn't accept any argument (also `self`), so it cannot be called as a method.

The simplest fix that came to my mind is to use `staticmethod` in `rest_framework`:

>     timer = staticmethod(time.time)

I have checked and this doesn't cause the failure of any test on `rest_framework` `master` branch - https://github.com/skarzi/django-rest-framework/pull/1

**Comment by skarzi** [comment]
However I am not sure why when running only a single test/test file `timer` is set to `fake_time` function, but when running a bunch of tests then `timer` is still set to `time.time` object (that returns mocked time correctly and somehow call `fake_time` "under the hood").

Do you have any ideas why such thing happens?

**Comment by tadeoos** [comment]
I encounter the same issue — in drf throttling, but it works for me individually but fails in the whole test suite when running with x-dist. I'm not using a freezegun in this test. Is it possible that freezegun is not thread safe and the mock leaks to tests that are run in parallel?

**Comment by pinguin999** [comment]
Hi 
here is an other "hack" to fix the problem with `rest_framework`'s `SimpleRateThrottle` without changing `rest_framework`'s code.

```
simple_timer = 'rest_framework.throttling.SimpleRateThrottle.timer'
with freeze_time(now) as frozen_datetime:
    with mock.patch(simple_timer, return_value=time.time()):
```

Hope it helps.

**Comment by ali-zahedi** [comment]
I’ve come up with two approaches that might be of help.

### **1. Using a Custom Context Manager**
We can create a custom context manager that ensures specific modules (like `ourproject.throttling`) are imported before `freeze_time` is applied. Here’s a code snippet for this:

```python
from contextlib import contextmanager
import freezegun

@contextmanager
def controlled_freeze_time(*args, **kwargs):
    """
    A context manager to control the behavior of freezegun.freeze_time.
    It ensures that certain modules are imported before applying freeze_time.
    """
    import ourproject.throttling  # Force the import of the throttling module

    with freezegun.freeze_time(*args, **kwargs):
        yield

# Example usage in tests
def test_example():
    with controlled_freeze_time("2023-10-10"):
        # Your test logic here
        result = some_functionality()
        assert result == expected_outcome
```

### **2. Patching `freeze_time`**
Alternatively, we can patch `freeze_time` directly to ensure that the necessary modules are imported before it’s applied. For instance, you can add the patch in your `conftest.py` like so:

```python
from contextlib import contextmanager
import freezegun

@contextmanager
def patched_freeze_time(*args, **kwargs):
    """
    A patch for freeze_time to ensure the import of specific modules 
    before applying the freeze_time decorator/context manager.
    """
    import ourproject.throttling  # noqa

    with freezegun.freeze_time(*args, **kwargs):
        yield

# Patching the original freeze_time with our custom version
freezegun.freeze_time = patched_freeze_time
```

In the test file:
```python
from freezegun import freeze_time

def test_example():
    with freeze_time("2023-10-10"):
        # Your test logic here
        result = some_functionality()
        assert result == expected_outcome
```
Both approaches should help ensure that `ourproject.throttling` is imported before `freeze_time` is applied, which could potentially resolve the issue. 

Would love to hear your thoughts and if there’s anything specific that should be adjusted or improved. If you give it a try, let us know how it works out! 😊

Happy coding! 🚀
