### ISSUE TITLE
'datetime.datetime' object has no attribute '_tz_offset'

### ISSUE THREAD

**Issue by kasium** [spulec/freezegun#400]
Below sample script fails with:

```
Traceback (most recent call last):
  File "dummy.py", line 12, in <module>
    test()
  File "dummy.py", line 8, in test
    initial_time - timedelta(minutes=20)
  File "venv/lib64/python3.7/site-packages/freezegun/api.py", line 379, in timestamp
    return (self - _EPOCH - self._tz_offset()).total_seconds()
```

```python
from datetime import datetime, timedelta
from freezegun import freeze_time

def test():
    initial_time = datetime.now()
    with freeze_time(initial_time):
        datetime.timestamp(initial_time - timedelta(minutes=20))

if __name__ == "__main__":
    test()
```

I use python 3.7.1 and freezegun 1.1.0

**Comment by kerrermanisNL** [comment]
Also running into this issue

**Comment by kasium** [comment]
So, this issue is now several months old. Any clue why it happens?

**Comment by kasium** [comment]
@kerrermanisNL 

Hey all,
so, the issue is, that inside the context managers, all datetime instances must be of type FakeTime. However if a datetime instance was previously created and is modified inside the context manager, this condition is no true. So, by moving the calculation above the context manager, the test will not fail.

However, this is quite hard to troubleshoot and is not documented. Therefore, some docs and maybe a nicer error would be great
