### ISSUE TITLE
freeze_time not working, if module name starts with "git"

### ISSUE THREAD

**Issue by the-working-rene** [spulec/freezegun#484]
The `@time_freeze` decorator does not work, when a module name starts with `git` and the test imports from that module.
Renaming the module (i.e. the folder and imports) to any string, which does not contains those three letters at the beginning, works.

I could reproduce the error with Python 3.10, see this minmal example. 
# Minimal Example Code
Only freezegun as external dependency
### git_module_name/minimal.py,
```python
from datetime import datetime as dt


def what_date_is_it_right_now():
    return dt.now()
```
###  other_module_name/minimal.py
 (exactly the same content in both)
```python
from datetime import datetime as dt


def what_date_is_it_right_now():
    return dt.now()
```

### test/test_minimal.py
```python
from datetime import datetime
from unittest import TestCase

from freezegun import freeze_time

from git_module_name.mininmal import what_date_is_it_right_now as what_date_is_it_right_now_git
from other_module_name.mininmal import what_date_is_it_right_now as what_date_is_it_right_now_other


class TimeTest(TestCase):
    @freeze_time("2001-02-03")
    def test_what_date_is_it_right_now_git(self):
        returned_time = what_date_is_it_right_now_git()
        self.assertEqual(returned_time, datetime.now())

    @freeze_time("2001-02-03")
    def test_what_date_is_it_right_now_other(self):
        returned_time = what_date_is_it_right_now_other()
        self.assertEqual(returned_time, datetime.now())
```
## Test Result

Running `python -m unittest tests.test_minimal.TimeTest` results in the first test failing and the second one passing:

```
F. 
======================================================================
FAIL: test_what_date_is_it_right_now_git (tests.test_minimal.TimeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\git\review\freezegun_minimal_example\.venv\lib\site-packages\freezegun\api.py", line 809, in wrapper
    result = func(*args, **kwargs)
  File "E:\git\review\freezegun_minimal_example\tests\test_minimal.py", line 14, in test_what_date_is_it_right_now_git
    self.assertEqual(returned_time, datetime.now())
AssertionError: datetime.datetime(2022, 11, 29, 11, 25, 35, 237124) != FakeDatetime(2001, 2, 3, 0, 0)

----------------------------------------------------------------------
Ran 2 tests in 0.073s

FAILED (failures=1)
```

**Comment by wimglenn** [comment]
I think this is because the string ["gi" is in the default ignores list](https://github.com/spulec/freezegun/blob/12e54da20e581a05fe64b7f5be16f764ff1dfab2/freezegun/config.py#L15) and the check in the ignore lists is pretty dumb, using [`str.startswith`](https://github.com/spulec/freezegun/blob/12e54da20e581a05fe64b7f5be16f764ff1dfab2/freezegun/api.py#L162).  Probably any module name which starts with "gi" will fail similarly.

**Comment by aaronoppenheimer** [comment]
Can confirm that freeze_time fails with a module called "gig"
